(stmt_prefix) @punctuation
(stmt_terminator) @punctuation.delimiter
(comment) @comment
"=" @operator
"," @punctuation.delimiter
(options) @attribute
(named_variable) @variable
(global_variable) @variable
(env_variable) @variable
(numbered_variable) @variable
(call) @keyword
