/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 49
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_stmt_prefix = 1,
  sym_stmt_terminator = 2,
  aux_sym_comment_token1 = 3,
  aux_sym_comment_token2 = 4,
  sym_named_variable = 5,
  sym_global_variable = 6,
  sym_env_variable = 7,
  sym_numbered_variable = 8,
  sym_type = 9,
  anon_sym_LPAREN = 10,
  aux_sym_substring_token1 = 11,
  anon_sym_DASH = 12,
  anon_sym_RPAREN = 13,
  sym_string = 14,
  sym_number = 15,
  sym_character = 16,
  sym_options = 17,
  anon_sym_EQ = 18,
  anon_sym_COMMA = 19,
  aux_sym__ldv_call_token1 = 20,
  aux_sym__ldv_fmt_3_token1 = 21,
  sym_source_file = 22,
  sym__line = 23,
  sym_statement = 24,
  sym__stmt_contents = 25,
  sym_comment = 26,
  sym_substring = 27,
  sym__variable = 28,
  sym__value_definition = 29,
  sym__assignment = 30,
  sym__assignment_delimited = 31,
  sym__ldv_call = 32,
  sym__ldv = 33,
  sym__ldv_fmt_1 = 34,
  sym__ldv_fmt_2 = 35,
  sym__ldv_fmt_3 = 36,
  aux_sym_source_file_repeat1 = 37,
  aux_sym_statement_repeat1 = 38,
  aux_sym__ldv_fmt_1_repeat1 = 39,
  aux_sym__ldv_fmt_2_repeat1 = 40,
  aux_sym__ldv_fmt_3_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_stmt_prefix] = "stmt_prefix",
  [sym_stmt_terminator] = "stmt_terminator",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_comment_token2] = "comment_token2",
  [sym_named_variable] = "named_variable",
  [sym_global_variable] = "global_variable",
  [sym_env_variable] = "env_variable",
  [sym_numbered_variable] = "numbered_variable",
  [sym_type] = "type",
  [anon_sym_LPAREN] = "(",
  [aux_sym_substring_token1] = "substring_token1",
  [anon_sym_DASH] = "-",
  [anon_sym_RPAREN] = ")",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_character] = "character",
  [sym_options] = "options",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [aux_sym__ldv_call_token1] = "call",
  [aux_sym__ldv_fmt_3_token1] = "options",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_statement] = "statement",
  [sym__stmt_contents] = "_stmt_contents",
  [sym_comment] = "comment",
  [sym_substring] = "substring",
  [sym__variable] = "_variable",
  [sym__value_definition] = "_value_definition",
  [sym__assignment] = "_assignment",
  [sym__assignment_delimited] = "_assignment_delimited",
  [sym__ldv_call] = "_ldv_call",
  [sym__ldv] = "_ldv",
  [sym__ldv_fmt_1] = "_ldv_fmt_1",
  [sym__ldv_fmt_2] = "_ldv_fmt_2",
  [sym__ldv_fmt_3] = "_ldv_fmt_3",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_statement_repeat1] = "statement_repeat1",
  [aux_sym__ldv_fmt_1_repeat1] = "_ldv_fmt_1_repeat1",
  [aux_sym__ldv_fmt_2_repeat1] = "_ldv_fmt_2_repeat1",
  [aux_sym__ldv_fmt_3_repeat1] = "_ldv_fmt_3_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_stmt_prefix] = sym_stmt_prefix,
  [sym_stmt_terminator] = sym_stmt_terminator,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [sym_named_variable] = sym_named_variable,
  [sym_global_variable] = sym_global_variable,
  [sym_env_variable] = sym_env_variable,
  [sym_numbered_variable] = sym_numbered_variable,
  [sym_type] = sym_type,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [aux_sym_substring_token1] = aux_sym_substring_token1,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_character] = sym_character,
  [sym_options] = sym_options,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym__ldv_call_token1] = aux_sym__ldv_call_token1,
  [aux_sym__ldv_fmt_3_token1] = sym_options,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_statement] = sym_statement,
  [sym__stmt_contents] = sym__stmt_contents,
  [sym_comment] = sym_comment,
  [sym_substring] = sym_substring,
  [sym__variable] = sym__variable,
  [sym__value_definition] = sym__value_definition,
  [sym__assignment] = sym__assignment,
  [sym__assignment_delimited] = sym__assignment_delimited,
  [sym__ldv_call] = sym__ldv_call,
  [sym__ldv] = sym__ldv,
  [sym__ldv_fmt_1] = sym__ldv_fmt_1,
  [sym__ldv_fmt_2] = sym__ldv_fmt_2,
  [sym__ldv_fmt_3] = sym__ldv_fmt_3,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_statement_repeat1] = aux_sym_statement_repeat1,
  [aux_sym__ldv_fmt_1_repeat1] = aux_sym__ldv_fmt_1_repeat1,
  [aux_sym__ldv_fmt_2_repeat1] = aux_sym__ldv_fmt_2_repeat1,
  [aux_sym__ldv_fmt_3_repeat1] = aux_sym__ldv_fmt_3_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_stmt_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_stmt_terminator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_named_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_global_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_env_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_numbered_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_substring_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_character] = {
    .visible = true,
    .named = true,
  },
  [sym_options] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__ldv_call_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__ldv_fmt_3_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__stmt_contents] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_substring] = {
    .visible = true,
    .named = true,
  },
  [sym__variable] = {
    .visible = false,
    .named = true,
  },
  [sym__value_definition] = {
    .visible = false,
    .named = true,
  },
  [sym__assignment] = {
    .visible = false,
    .named = true,
  },
  [sym__assignment_delimited] = {
    .visible = false,
    .named = true,
  },
  [sym__ldv_call] = {
    .visible = false,
    .named = true,
  },
  [sym__ldv] = {
    .visible = false,
    .named = true,
  },
  [sym__ldv_fmt_1] = {
    .visible = false,
    .named = true,
  },
  [sym__ldv_fmt_2] = {
    .visible = false,
    .named = true,
  },
  [sym__ldv_fmt_3] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__ldv_fmt_1_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__ldv_fmt_2_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__ldv_fmt_3_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
};

static const TSCharacterRange sym_type_character_set_1[] = {
  {'A', 'A'}, {'F', 'F'}, {'H', 'I'}, {'O', 'O'}, {'S', 'S'}, {'a', 'a'}, {'f', 'f'}, {'h', 'i'},
  {'o', 'o'}, {'s', 's'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(57);
      ADVANCE_MAP(
        '"', 3,
        '\'', 5,
        '(', 74,
        ')', 77,
        ',', 90,
        '-', 76,
        '.', 59,
        '<', 4,
        '=', 89,
        '@', 58,
        'L', 83,
        'l', 83,
        'V', 86,
        'v', 86,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      if (set_contains(sym_type_character_set_1, 10, lookahead)) ADVANCE(87);
      if (('B' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(62);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '.') ADVANCE(54);
      if (lookahead == '<') ADVANCE(4);
      if (lookahead == 'V' ||
          lookahead == 'v') ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(78);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '$') ADVANCE(44);
      if (lookahead == '*') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(41);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(78);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '(', 74,
        ',', 90,
        '.', 59,
        '<', 4,
        '=', 89,
        'L', 48,
        'l', 48,
        'V', 51,
        'v', 51,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (set_contains(sym_type_character_set_1, 10, lookahead)) ADVANCE(52);
      END_STATE();
    case 7:
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == ',') ADVANCE(90);
      if (lookahead == '.') ADVANCE(59);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 8:
      if (lookahead == ')') ADVANCE(82);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(63);
      END_STATE();
    case 11:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 14:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 15:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 16:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 18:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 19:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 20:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 21:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 22:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 24:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 25:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 26:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 27:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 28:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 29:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 30:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 31:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 32:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 33:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 34:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 35:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 36:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 37:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 38:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 39:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 40:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 41:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 42:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 43:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 44:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 45:
      if (lookahead == '>') ADVANCE(63);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 46:
      if (lookahead == '>') ADVANCE(65);
      END_STATE();
    case 47:
      if (lookahead == '>') ADVANCE(64);
      END_STATE();
    case 48:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(50);
      END_STATE();
    case 49:
      if (lookahead == 'Q' ||
          lookahead == 'q') ADVANCE(84);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(49);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 50:
      if (lookahead == 'V' ||
          lookahead == 'v') ADVANCE(91);
      END_STATE();
    case 51:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 52:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 53:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 54:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(80);
      END_STATE();
    case 55:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 56:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(8);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_stmt_prefix);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_stmt_terminator);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(60);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(61);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '\n') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_named_variable);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_global_variable);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_env_variable);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_numbered_variable);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_numbered_variable);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_numbered_variable);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_type);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_type);
      if (lookahead == '.') ADVANCE(53);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_type);
      if (lookahead == '.') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_type);
      if (lookahead == '.') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_type);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_substring_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(54);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_character);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_options);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(85);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_options);
      if (lookahead == 'Q' ||
          lookahead == 'q') ADVANCE(84);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_options);
      if (lookahead == 'V' ||
          lookahead == 'v') ADVANCE(88);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_options);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_options);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_options);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym__ldv_call_token1);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 7},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 49},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 60},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 60},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_stmt_prefix] = ACTIONS(1),
    [sym_stmt_terminator] = ACTIONS(1),
    [sym_named_variable] = ACTIONS(1),
    [sym_global_variable] = ACTIONS(1),
    [sym_env_variable] = ACTIONS(1),
    [sym_numbered_variable] = ACTIONS(1),
    [sym_type] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [aux_sym_substring_token1] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_options] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [aux_sym__ldv_call_token1] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(45),
    [sym__line] = STATE(12),
    [sym_statement] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_stmt_prefix] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(7), 1,
      sym_stmt_terminator,
    ACTIONS(9), 1,
      aux_sym__ldv_call_token1,
    STATE(8), 1,
      sym__ldv_call,
    STATE(2), 6,
      sym__stmt_contents,
      sym__ldv,
      sym__ldv_fmt_1,
      sym__ldv_fmt_2,
      sym__ldv_fmt_3,
      aux_sym_statement_repeat1,
  [18] = 4,
    ACTIONS(12), 1,
      sym_stmt_terminator,
    ACTIONS(14), 1,
      aux_sym__ldv_call_token1,
    STATE(8), 1,
      sym__ldv_call,
    STATE(4), 6,
      sym__stmt_contents,
      sym__ldv,
      sym__ldv_fmt_1,
      sym__ldv_fmt_2,
      sym__ldv_fmt_3,
      aux_sym_statement_repeat1,
  [36] = 4,
    ACTIONS(14), 1,
      aux_sym__ldv_call_token1,
    ACTIONS(16), 1,
      sym_stmt_terminator,
    STATE(8), 1,
      sym__ldv_call,
    STATE(2), 6,
      sym__stmt_contents,
      sym__ldv,
      sym__ldv_fmt_1,
      sym__ldv_fmt_2,
      sym__ldv_fmt_3,
      aux_sym_statement_repeat1,
  [54] = 4,
    ACTIONS(18), 2,
      sym_named_variable,
      sym_numbered_variable,
    ACTIONS(20), 2,
      sym_global_variable,
      sym_env_variable,
    ACTIONS(22), 2,
      sym_string,
      sym_number,
    STATE(29), 2,
      sym__variable,
      sym__value_definition,
  [71] = 5,
    STATE(20), 1,
      sym__assignment_delimited,
    STATE(43), 1,
      sym__variable,
    STATE(44), 1,
      sym__assignment,
    ACTIONS(18), 2,
      sym_named_variable,
      sym_numbered_variable,
    ACTIONS(20), 2,
      sym_global_variable,
      sym_env_variable,
  [89] = 4,
    ACTIONS(26), 1,
      sym_type,
    ACTIONS(28), 1,
      anon_sym_LPAREN,
    STATE(18), 1,
      sym_substring,
    ACTIONS(24), 4,
      sym_stmt_terminator,
      anon_sym_EQ,
      anon_sym_COMMA,
      aux_sym__ldv_call_token1,
  [105] = 5,
    ACTIONS(30), 1,
      anon_sym_COMMA,
    STATE(19), 1,
      sym__assignment,
    STATE(43), 1,
      sym__variable,
    ACTIONS(18), 2,
      sym_named_variable,
      sym_numbered_variable,
    ACTIONS(20), 2,
      sym_global_variable,
      sym_env_variable,
  [123] = 5,
    STATE(32), 1,
      sym__assignment_delimited,
    STATE(43), 1,
      sym__variable,
    STATE(44), 1,
      sym__assignment,
    ACTIONS(18), 2,
      sym_named_variable,
      sym_numbered_variable,
    ACTIONS(20), 2,
      sym_global_variable,
      sym_env_variable,
  [141] = 4,
    STATE(30), 1,
      sym__assignment,
    STATE(43), 1,
      sym__variable,
    ACTIONS(18), 2,
      sym_named_variable,
      sym_numbered_variable,
    ACTIONS(20), 2,
      sym_global_variable,
      sym_env_variable,
  [156] = 4,
    STATE(14), 1,
      sym__variable,
    STATE(17), 1,
      sym__assignment,
    ACTIONS(18), 2,
      sym_named_variable,
      sym_numbered_variable,
    ACTIONS(20), 2,
      sym_global_variable,
      sym_env_variable,
  [171] = 3,
    ACTIONS(5), 1,
      sym_stmt_prefix,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
    STATE(13), 3,
      sym__line,
      sym_statement,
      aux_sym_source_file_repeat1,
  [183] = 3,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    ACTIONS(36), 1,
      sym_stmt_prefix,
    STATE(13), 3,
      sym__line,
      sym_statement,
      aux_sym_source_file_repeat1,
  [195] = 4,
    ACTIONS(41), 1,
      anon_sym_EQ,
    ACTIONS(43), 1,
      anon_sym_COMMA,
    STATE(23), 1,
      aux_sym__ldv_fmt_2_repeat1,
    ACTIONS(39), 2,
      sym_stmt_terminator,
      aux_sym__ldv_call_token1,
  [209] = 3,
    STATE(31), 1,
      sym__variable,
    ACTIONS(18), 2,
      sym_named_variable,
      sym_numbered_variable,
    ACTIONS(20), 2,
      sym_global_variable,
      sym_env_variable,
  [221] = 3,
    ACTIONS(47), 1,
      anon_sym_COMMA,
    STATE(21), 1,
      aux_sym__ldv_fmt_1_repeat1,
    ACTIONS(45), 2,
      sym_stmt_terminator,
      aux_sym__ldv_call_token1,
  [232] = 3,
    ACTIONS(47), 1,
      anon_sym_COMMA,
    STATE(24), 1,
      aux_sym__ldv_fmt_1_repeat1,
    ACTIONS(49), 2,
      sym_stmt_terminator,
      aux_sym__ldv_call_token1,
  [243] = 1,
    ACTIONS(51), 4,
      sym_stmt_terminator,
      anon_sym_EQ,
      anon_sym_COMMA,
      aux_sym__ldv_call_token1,
  [250] = 3,
    ACTIONS(47), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym__ldv_fmt_1_repeat1,
    ACTIONS(53), 2,
      sym_stmt_terminator,
      aux_sym__ldv_call_token1,
  [261] = 3,
    ACTIONS(57), 1,
      anon_sym_COMMA,
    STATE(26), 1,
      aux_sym__ldv_fmt_3_repeat1,
    ACTIONS(55), 2,
      sym_stmt_terminator,
      aux_sym__ldv_call_token1,
  [272] = 3,
    ACTIONS(61), 1,
      anon_sym_COMMA,
    STATE(21), 1,
      aux_sym__ldv_fmt_1_repeat1,
    ACTIONS(59), 2,
      sym_stmt_terminator,
      aux_sym__ldv_call_token1,
  [283] = 3,
    ACTIONS(66), 1,
      anon_sym_COMMA,
    STATE(22), 1,
      aux_sym__ldv_fmt_2_repeat1,
    ACTIONS(64), 2,
      sym_stmt_terminator,
      aux_sym__ldv_call_token1,
  [294] = 3,
    ACTIONS(43), 1,
      anon_sym_COMMA,
    STATE(22), 1,
      aux_sym__ldv_fmt_2_repeat1,
    ACTIONS(69), 2,
      sym_stmt_terminator,
      aux_sym__ldv_call_token1,
  [305] = 3,
    ACTIONS(47), 1,
      anon_sym_COMMA,
    STATE(21), 1,
      aux_sym__ldv_fmt_1_repeat1,
    ACTIONS(71), 2,
      sym_stmt_terminator,
      aux_sym__ldv_call_token1,
  [316] = 2,
    ACTIONS(75), 1,
      sym_character,
    ACTIONS(73), 3,
      sym_stmt_terminator,
      anon_sym_COMMA,
      aux_sym__ldv_call_token1,
  [325] = 3,
    ACTIONS(57), 1,
      anon_sym_COMMA,
    STATE(27), 1,
      aux_sym__ldv_fmt_3_repeat1,
    ACTIONS(77), 2,
      sym_stmt_terminator,
      aux_sym__ldv_call_token1,
  [336] = 3,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    STATE(27), 1,
      aux_sym__ldv_fmt_3_repeat1,
    ACTIONS(79), 2,
      sym_stmt_terminator,
      aux_sym__ldv_call_token1,
  [347] = 1,
    ACTIONS(84), 4,
      sym_stmt_terminator,
      anon_sym_EQ,
      anon_sym_COMMA,
      aux_sym__ldv_call_token1,
  [354] = 1,
    ACTIONS(86), 3,
      sym_stmt_terminator,
      anon_sym_COMMA,
      aux_sym__ldv_call_token1,
  [360] = 1,
    ACTIONS(59), 3,
      sym_stmt_terminator,
      anon_sym_COMMA,
      aux_sym__ldv_call_token1,
  [366] = 1,
    ACTIONS(64), 3,
      sym_stmt_terminator,
      anon_sym_COMMA,
      aux_sym__ldv_call_token1,
  [372] = 1,
    ACTIONS(79), 3,
      sym_stmt_terminator,
      anon_sym_COMMA,
      aux_sym__ldv_call_token1,
  [378] = 1,
    ACTIONS(88), 3,
      sym_stmt_terminator,
      anon_sym_COMMA,
      aux_sym__ldv_call_token1,
  [384] = 2,
    ACTIONS(90), 1,
      sym_options,
    ACTIONS(92), 1,
      aux_sym__ldv_fmt_3_token1,
  [391] = 1,
    ACTIONS(94), 2,
      ts_builtin_sym_end,
      sym_stmt_prefix,
  [396] = 1,
    ACTIONS(96), 2,
      ts_builtin_sym_end,
      sym_stmt_prefix,
  [401] = 2,
    ACTIONS(98), 1,
      aux_sym_comment_token1,
    STATE(38), 1,
      sym_comment,
  [408] = 1,
    ACTIONS(100), 2,
      ts_builtin_sym_end,
      sym_stmt_prefix,
  [413] = 2,
    ACTIONS(98), 1,
      aux_sym_comment_token1,
    STATE(36), 1,
      sym_comment,
  [420] = 1,
    ACTIONS(102), 1,
      aux_sym_substring_token1,
  [424] = 1,
    ACTIONS(104), 1,
      aux_sym_comment_token2,
  [428] = 1,
    ACTIONS(106), 1,
      anon_sym_DASH,
  [432] = 1,
    ACTIONS(41), 1,
      anon_sym_EQ,
  [436] = 1,
    ACTIONS(108), 1,
      anon_sym_COMMA,
  [440] = 1,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
  [444] = 1,
    ACTIONS(112), 1,
      aux_sym_substring_token1,
  [448] = 1,
    ACTIONS(114), 1,
      anon_sym_RPAREN,
  [452] = 1,
    ACTIONS(116), 1,
      sym_number,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 18,
  [SMALL_STATE(4)] = 36,
  [SMALL_STATE(5)] = 54,
  [SMALL_STATE(6)] = 71,
  [SMALL_STATE(7)] = 89,
  [SMALL_STATE(8)] = 105,
  [SMALL_STATE(9)] = 123,
  [SMALL_STATE(10)] = 141,
  [SMALL_STATE(11)] = 156,
  [SMALL_STATE(12)] = 171,
  [SMALL_STATE(13)] = 183,
  [SMALL_STATE(14)] = 195,
  [SMALL_STATE(15)] = 209,
  [SMALL_STATE(16)] = 221,
  [SMALL_STATE(17)] = 232,
  [SMALL_STATE(18)] = 243,
  [SMALL_STATE(19)] = 250,
  [SMALL_STATE(20)] = 261,
  [SMALL_STATE(21)] = 272,
  [SMALL_STATE(22)] = 283,
  [SMALL_STATE(23)] = 294,
  [SMALL_STATE(24)] = 305,
  [SMALL_STATE(25)] = 316,
  [SMALL_STATE(26)] = 325,
  [SMALL_STATE(27)] = 336,
  [SMALL_STATE(28)] = 347,
  [SMALL_STATE(29)] = 354,
  [SMALL_STATE(30)] = 360,
  [SMALL_STATE(31)] = 366,
  [SMALL_STATE(32)] = 372,
  [SMALL_STATE(33)] = 378,
  [SMALL_STATE(34)] = 384,
  [SMALL_STATE(35)] = 391,
  [SMALL_STATE(36)] = 396,
  [SMALL_STATE(37)] = 401,
  [SMALL_STATE(38)] = 408,
  [SMALL_STATE(39)] = 413,
  [SMALL_STATE(40)] = 420,
  [SMALL_STATE(41)] = 424,
  [SMALL_STATE(42)] = 428,
  [SMALL_STATE(43)] = 432,
  [SMALL_STATE(44)] = 436,
  [SMALL_STATE(45)] = 440,
  [SMALL_STATE(46)] = 444,
  [SMALL_STATE(47)] = 448,
  [SMALL_STATE(48)] = 452,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_statement_repeat1, 2, 0, 0),
  [9] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [12] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [14] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [16] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [18] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [20] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [22] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__variable, 1, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ldv_fmt_2, 4, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ldv_fmt_1, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ldv_fmt_1, 4, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__variable, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ldv_fmt_1, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ldv_fmt_3, 4, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__ldv_fmt_1_repeat1, 2, 0, 0),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__ldv_fmt_1_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__ldv_fmt_2_repeat1, 2, 0, 0),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__ldv_fmt_2_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ldv_fmt_2, 5, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ldv_fmt_1, 5, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__assignment_delimited, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ldv_fmt_3, 5, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__ldv_fmt_3_repeat1, 2, 0, 0),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__ldv_fmt_3_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_substring, 5, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__assignment, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__assignment_delimited, 4, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 4, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [110] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bis(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "bis",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
